<?php
namespace Elemacy\Modules\DynamicTags\Tags\Utility;

use Elementor\Controls_Manager;
use Elementor\Core\DynamicTags\Tag;
use Elementor\Modules\DynamicTags\Module;

if (!defined('ABSPATH')) {
	exit;
}

class Shortcode extends Tag
{

	public function get_name()
	{
		return 'elemacy-shortcode';
	}

	public function get_title()
	{
		return esc_html__('Shortcode', 'elemacy');
	}

	public function get_group()
	{
		return 'elemacy';
	}

	public function get_categories()
	{
		return [Module::TEXT_CATEGORY];
	}

	public function is_settings_required()
	{
		return true;
	}

	protected function register_controls()
	{
		$this->add_control(
			'shortcode',
			[
				'label' => esc_html__('Shortcode', 'elemacy'),
				'type' => Controls_Manager::TEXTAREA,
				'placeholder' => '[gallery]',
				'ai' => [
					'active' => false,
				],
			]
		);
	}

	public function render()
	{
		$shortcode = $this->get_settings('shortcode');

		if (empty($shortcode)) {
			return;
		}

		$value = do_shortcode(shortcode_unautop($shortcode));

		// Shortcode output is generated by WordPress/registered handlers and is intended as rendered HTML.
		echo $value; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
	}
}
