<?php

/**
 * @var array{title:string,message:string,action_url:?string,button_label:string} $data
 */

defined('ABSPATH') || exit;
?>
<div class="notice elemacy-dep-notice">
    <div class="elemacy-dep-notice__icon" aria-hidden="true">
        <?php // Trusted SVG generated by the shared brand helper. ?>
        <?php echo \Elemacy\Support\Brand::svg_mark(26); ?>
    </div>
    <div class="elemacy-dep-notice__body">
        <h2 class="elemacy-dep-notice__title"><?php echo esc_html($data['title']); ?></h2>
        <p class="elemacy-dep-notice__text"><?php echo esc_html($data['message']); ?></p>
    </div>
    <?php if ($data['action_url']) : ?>
        <a class="elemacy-dep-notice__button" href="<?php echo esc_url($data['action_url']); ?>">
            <?php echo esc_html($data['button_label']); ?>
        </a>
    <?php endif; ?>
</div>
